#!/bin/bash

set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "$0")/..";pwd)"
cd "$PROJECT_ROOT"

echo "██████████████████████████████  mypy  ██████████████████████████████"
poetry run mypy src/{{cookiecutter.project_slug}} tests
echo "██████████████████████████████ pylint ██████████████████████████████"
poetry run pylint src/{{cookiecutter.project_slug}} tests
