#!/bin/bash

set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "$0")/..";pwd)"
cd "$PROJECT_ROOT"

if [[ "$#" -gt 0 ]] && [[ "$1" = "check" ]]; then
    # Check only

    echo "████████████████████████████   ruff   █████████████████████████████"
    poetry run ruff .
    echo "████████████████████████████   black   █████████████████████████████"
    poetry run black --check src/{{cookiecutter.project_slug}} tests
else
    # Reformat

    echo "████████████████████████████   ruff   █████████████████████████████"
    poetry run ruff .
    echo "████████████████████████████   black   █████████████████████████████"
    poetry run black src/{{cookiecutter.project_slug}} tests
fi
